from telebot import types

startmenu_markup = types.ReplyKeyboardMarkup(row_width=3, resize_keyboard=True)
startmenu_markup_btn1 = types.KeyboardButton('Каталог📕')
startmenu_markup_btn2 = types.KeyboardButton('Помощь💡')
startmenu_markup_btn3 = types.KeyboardButton('Пожертвовать🤑')
startmenu_markup.add(startmenu_markup_btn1, startmenu_markup_btn2, startmenu_markup_btn3)

menu_markup = types.ReplyKeyboardMarkup(row_width=3, resize_keyboard=True)
menu_markup_btn1 = types.KeyboardButton('Зарубежная')
menu_markup_btn2 = types.KeyboardButton('Русская')
menu_markup_btn3 = types.KeyboardButton('Главное меню')
menu_markup.add(menu_markup_btn1, menu_markup_btn2, menu_markup_btn3)

genre_markup = types.ReplyKeyboardMarkup(row_width=4, resize_keyboard=True)
genre_markup_btn1 = types.KeyboardButton('Детективы')
genre_markup_btn2 = types.KeyboardButton('История')
genre_markup_btn3 = types.KeyboardButton('Классика')
genre_markup_btn4 = types.KeyboardButton('Нон_фикшен')
genre_markup_btn5 = types.KeyboardButton('Поэзия')
genre_markup_btn6 = types.KeyboardButton('Подросткам')
genre_markup_btn7 = types.KeyboardButton('Политика')
genre_markup_btn8 = types.KeyboardButton('Романы')
genre_markup_btn9 = types.KeyboardButton('Триллер')
genre_markup_btn10 = types.KeyboardButton('Фантастика')
genre_markup_btn11 = types.KeyboardButton('Хорор')
genre_markup_btn12 = types.KeyboardButton('Художественные')
genre_markup_btn13 = types.KeyboardButton('Назад')
genre_markup.add(genre_markup_btn1, genre_markup_btn2, genre_markup_btn3, genre_markup_btn4, genre_markup_btn5, genre_markup_btn6, genre_markup_btn7, genre_markup_btn8, genre_markup_btn9, genre_markup_btn10, genre_markup_btn11, genre_markup_btn12, genre_markup_btn13)

kategory_markup = types.ReplyKeyboardMarkup(row_width=3, resize_keyboard=True)
kategory_markup_btn1 = types.KeyboardButton('Аудиосказки')
kategory_markup_btn16 = types.KeyboardButton('Аудиоспектакли')
kategory_markup_btn2 = types.KeyboardButton('Бизнес литература')
kategory_markup_btn3 = types.KeyboardButton('Зарубежная классика')
kategory_markup_btn4 = types.KeyboardButton('Русская классика')
kategory_markup_btn5 = types.KeyboardButton('Инвестиции')
kategory_markup_btn6 = types.KeyboardButton('Иностранные языки')
kategory_markup_btn7 = types.KeyboardButton('Личностный рост')
kategory_markup_btn8 = types.KeyboardButton('Профессиональная литература')
kategory_markup_btn9 = types.KeyboardButton('Современная зарубежная литература')
kategory_markup_btn10 = types.KeyboardButton('Современная русская литература')
kategory_markup_btn11 = types.KeyboardButton('Философия и психология')
kategory_markup_btn12 = types.KeyboardButton('Школьная программа')
kategory_markup_btn13 = types.KeyboardButton('Эротика')
kategory_markup_btn14 = types.KeyboardButton('Жанры')
kategory_markup_btn15 = types.KeyboardButton('Главное меню')
kategory_markup.add(kategory_markup_btn1, kategory_markup_btn16, kategory_markup_btn2, kategory_markup_btn3, kategory_markup_btn4, kategory_markup_btn5, kategory_markup_btn6, kategory_markup_btn7, kategory_markup_btn8, kategory_markup_btn9, kategory_markup_btn10, kategory_markup_btn11, kategory_markup_btn12, kategory_markup_btn13, kategory_markup_btn14, kategory_markup_btn15)
